name: clingoLP
channels:
  - sthiele
  - potassco
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2019.11.28=hecc5488_0
  - certifi=2019.11.28=py37hc8dfbb8_1
  - clingo=5.4.0=py37lua53hf484d3e_0
  - clingolp=0.1.0=py_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_5
  - liblapack=3.8.0=14_openblas
  - libopenblas=0.3.7=h5ec1e0e_6
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - lp_solve=5.5.2.5=h14c3975_1001
  - lpsolve55=5.5=py37hc1659b7_1001
  - lua=5.3.4=h7b6447c_0
  - ncurses=6.2=he6710b0_0
  - numpy=1.18.1=py37h95a1406_0
  - openssl=1.1.1e=h516909a_0
  - pip=20.0.2=py37_1
  - python=3.7.6=h0371630_2
  - python_abi=3.7=1_cp37m
  - readline=7.0=h7b6447c_5
  - setuptools=46.0.0=py37_0
  - sqlite=3.31.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.34.2=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
prefix: /home/sthiele/miniconda3/envs/clingoLP
